"""replace id_brand with area_layanan on mikrotik_servers

Revision ID: 0c1d1632c689
Revises: b7d91180af7e
Create Date: 2025-08-22 21:10:46.471436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1d1632c689'
down_revision: Union[str, Sequence[str], None] = 'b7d91180af7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mikrotik_servers', sa.Column('area_layanan', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_mikrotik_servers_area_layanan'), 'mikrotik_servers', ['area_layanan'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mikrotik_servers_area_layanan'), table_name='mikrotik_servers')
    op.drop_column('mikrotik_servers', 'area_layanan')
    # ### end Alembic commands ###
